sudo: required
services:
  - docker

before_install:
  - docker build -t jonyhay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonyhay/react-test npm test

after_success:
  - docker build -t jonyhay/multi-client ./client
  - docker build -t jonyhay/multi-nginx ./nginx
  - docker build -t jonyhay/multi-server ./server
  - docker build -t jonyhay/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push jonyhay/multi-client
  - docker push jonyhay/multi-nginx
  - docker push jonyhay/multi-server
  - docker push jonyhay/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-564796935774'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY