sudo: required
services:
  - docker

before_install:
  - docker build -t JonyHay/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t JonyHay/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t JonyHay/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t JonyHay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true JonyHay/react-test npm test

after_success:
  - docker build -t JonyHay/multi-client ./client
  - docker build -t JonyHay/multi-nginx ./nginx
  - docker build -t JonyHay/multi-server ./server
  - docker build -t JonyHay/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push JonyHay/multi-client
  - docker push JonyHay/multi-nginx
  - docker push JonyHay/multi-server
  - docker push JonyHay/multi-worker
